---
- name: Restart Foreman
  hosts: all
  become: true
  gather_facts: false
  tasks:
  - name: Restart Foreman
    shell: foreman-maintain health check --plaintext -y
    register: foreman_maintain_output
  
  - name: Show result of maintain task
    debug:
      var: foreman_maintain_output
